import { useEffect } from "react";
import ArcAnalytics from "../../assets/image/portfolio/ArcAnalytics.png";
import ArcApps from "../../assets/image/portfolio/ArcApps.png";
import ArcPOS from "../../assets/image/portfolio/ArcPOS.png";
import CBHIS from "../../assets/image/portfolio/CBHIS.png";
import CMIS from "../../assets/image/portfolio/CMIS.png";
import CarePro from "../../assets/image/portfolio/CarePro.png";
import MeetingRoom from "../../assets/image/portfolio/MeetingRoom.png";
import TUSO from "../../assets/image/portfolio/TUSO.png";
import Title from "../../components/title/Title";
import Container from "../../container/Container";

function Portfolio() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="pt-24 bg-[#F4F5FA] pb-44">
      <Container>
        <div className="w-full">
          <Title title="Portfolio" />

          <div className="mt-24 grid sm:grid-cols-2 xl:grid-cols-3 gap-5 w-full">
            <PortfolioBox
              item={{
                title: "SmartCare Pro",
                desc: "An advanced EHR system designed to revolutionize healthcare in Zambia through digital transformation. Our data-driven approach goes beyond health informatics, enhancing clinical decision support systems and prioritizing patient-centered care.",
                image: CarePro,
              }}
            />
            <PortfolioBox
              item={{
                title: "TUSO",
                desc: "A next-gen IT Helpdesk Management platform to unleash your full potential for productivity. Streamline and scale IT Operations, Manage IT Assets, Track progress and Drive results",
                image: TUSO,
              }}
            />
            <PortfolioBox
              item={{
                title: "Arc POS",
                desc: "Handheld-terminal based Point of Sale software that is user friendly, extremely flexible, and fully integrated with inventory for real-time stock control. It even works both online and offline.",
                image: ArcPOS,
              }}
            />
            <PortfolioBox
              item={{
                title: "Arc Analytics",
                desc: "Modern data exploration and visualization plat - form. It’s fast, lightweight, intuitive, and loaded with options that make it easy for users of all skill sets to explore and visualize their data, from simple line charts to highly detailed geos - patial charts",
                image: ArcAnalytics,
              }}
            />
            <PortfolioBox
              item={{
                title: "ArcApps Enterprise Resource Planning",
                desc: "A versatile and agile Enterprise Resource Plan - ner adaptable to businesses of all sizes. From Retail, Distribution, Services to Manufacturing, this application suite is designed for both sim - plicity and power.",
                image: ArcApps,
              }}
            />
            <PortfolioBox
              item={{
                title: "Community Based Health Information System",
                desc: "CBHIS in Eswatini facilitates the seamless sharing and use of information between community-based services and higher-level health facilities. The data collected by CBHIS integrates into the national health manage - ment information system. The information generated by community health services now plays a crucial role in decision-making at all levels, ensuring compliance with natio - nal and international health goals.",
                image: CBHIS,
              }}
            />
            <PortfolioBox
              item={{
                title: "Client Management Information System",
                desc: "The Client Management Information System (CMIS) is a vital EHR application that supports Eswatini’s goals for epidemic control, aiming to achieve an AIDS-Free Generation, enhance HIV and TB patient care, and improve overall patient services.",
                image: CMIS,
              }}
            />
            <PortfolioBox
              item={{
                title: "Arc Workspace",
                desc: "The workspace rebalancing platform for leaner space usage, smart desk/room booking, better collaboration and smoo - ther hybrid work",
                image: MeetingRoom,
              }}
            />
          </div>
        </div>
      </Container>
    </div>
  );
}

export default Portfolio;

interface portfolioType {
  item: {
    title: string;
    desc: string;
    image: string;
  };
}
const PortfolioBox = ({ item }: portfolioType) => {
  return (
    <div className="shadow-lg p-5 bg-white portfolio-box relative rounded-lg overflow-hidden">
      <img
        src={item.image}
        alt=""
        className="h-[300px] object-contain transition-all"
      />
      <div className="content">
        <p>{item.desc}</p>
      </div>
      <h1 className="font-[font-500] text-[20px] text-center mt-5 border-t pt-3 flex justify-center items-center">
        {item.title}
      </h1>
    </div>
  );
};
